Add Assumed Identity examples - Adds Assumed Identity to Docker Compose - Adds new tests to demonstrate POC with the DefaultAzureCredential - Updates documentation
Signed-off-by: Esta Nagy <nagyesta@gmail.com>

diff --git a/.github/workflows/python.yml b/.github/workflows/python.yml
--- a/.github/workflows/python.yml
+++ b/.github/workflows/python.yml
@@ -34,9 +34,13 @@ jobs:
         docker-compose up -d
         sleep 10
         docker ps
+        if [ $(docker ps | grep nagyesta | wc -l) -ne 2 ]; then echo "ERROR: Some containers are not running"; exit 1; fi
     - name: Test with pytest
       env:
         REQUESTS_CA_BUNDLE: lowkeyvault.pem
+        AZURE_POD_IDENTITY_AUTHORITY_HOST: http://localhost:8080
+        IDENTITY_ENDPOINT: http://localhost:8080/metadata/identity/oauth2/token
+        IMDS_ENDPOINT: http://localhost:8080
       run: |
         python -m pytest tests/test.py
     - name: Stop container
