Add note about new Token endpoint
Signed-off-by: Esta Nagy <nagyesta@gmail.com>

diff --git a/.github/workflows/python.yml b/.github/workflows/python.yml
--- a/.github/workflows/python.yml
+++ b/.github/workflows/python.yml
@@ -19,7 +19,8 @@ jobs:
         python-version: ["3.8", "3.9", "3.10"]
 
     steps:
-    - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4
+    - name: Checkout
+      uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4
     - name: Set up Python ${{ matrix.python-version }}
       uses: actions/setup-python@82c7e631bb3cdc910f68e0081d67478d79c6982d # v5
       with:
@@ -34,7 +35,7 @@ jobs:
         docker-compose up -d
         sleep 10
         docker ps
-        if [ $(docker ps | grep nagyesta | wc -l) -ne 2 ]; then echo "ERROR: Some containers are not running"; exit 1; fi
+        if [ $(docker ps | grep nagyesta | wc -l) -ne 1 ]; then echo "ERROR: Some containers are not running"; exit 1; fi
     - name: Test with pytest
       env:
         REQUESTS_CA_BUNDLE: lowkeyvault.pem
